# Generated by Django 4.1.4 on 2022-12-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_date_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
    ]
